---
name: docker checker

on:
  pull_request:
    branches:
      - 'master'

  push:
    branches:
      - 'master'

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Analyze image efficiency
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install jinjalint
        run: |
          python -m pip install jinjalint
      - name: Lint with Jinjalint
        run: |
          jinjalinter templates/
          jinjalinter userpod/