---
name: docker checker

on:
  pull_request:
    branches:
      - 'master'

  push:
    branches:
      - 'master'

jobs:
  lint:
    runs-on: ubuntu-latest
    name: lint templates
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install curlylint
        run: |
          python3 -m pip install curlylint
      - name: Lint with curlylint
        run: |
          python3 -m curlylint templates/
          python3 -m curlylint userpod/
